apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helsinki-weather-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/floppino/shiny-octo-system.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: helsinki-weather
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true